scenarios:
  familiarization:
    map_id: 1.0
    world: worlds/familiarization.world
    bag_prefix: Familiarization
  train1:
    map_id: 2.0
    world: worlds/labyrinth1.world
    bag_prefix: Train1
  train2:
    map_id: 3.0
    world: worlds/labyrinth1.world
    bag_prefix: Train2
  train3:
    map_id: 4.0
    world: worlds/labyrinth1.world
    bag_prefix: Train3
  train4:
    map_id: 5.0
    world: worlds/labyrinth1.world
    bag_prefix: Train4
  test1:
    map_id: 6.0
    world: worlds/mid_tests.world
    bag_prefix: Test1
  train5:
    map_id: 7.0
    world: worlds/labyrinth2.world
    bag_prefix: Train5
  train6:
    map_id: 8.0
    world: worlds/labyrinth2.world
    bag_prefix: Train6
  train7:
    map_id: 9.0
    world: worlds/labyrinth2.world
    bag_prefix: Train7
  train8:
    map_id: 10.0
    world: worlds/labyrinth2.world
    bag_prefix: Train8
  test2:
    map_id: 11.0
    world: worlds/mid_tests.world
    bag_prefix: Test2
  final_test:
    map_id: 12.0
    world: worlds/final_test.world
    bag_prefix: FinalTest